### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by haikusw**
Hopefully just part of the transcription process and not part of the historical record kept that way for accuracy…

### CODE REVIEW

**Comment by snipe** [comment]
Sorry I missed this originally - the changes are good.

**Comment by haikusw** [comment]
No worries.  I was just cleaning out old unmerged PRs.  I felt no sting about it (it's unsolicited suggestions on a piece of creative work after all - a bit cheeky to even submit a PR :) ).

**Comment by snipe** [comment]
Heh, no worries. If I didn't want PRs, I wouldn't have opened up issues on this repo. ;)

I don't recall if the guy who transcribed it did it via OCR or if it was hysterical typos - either way, I'm grateful for it existing, typos and all. I thought this work was lost literally 30 years ago. :)

**Comment by haikusw** [comment]
:) Thanks.  Agree that it looks like the OCR flavor of errors.

**Comment by snipe** [comment]
LMAO "hysterical typos" - that may be the best typos I've ever made

**Comment by snipe** [comment]
I can't even imagine what word I was *trying* to write before autocorrect made it weird. 😂

**Comment by haikusw** [comment]
:)

"hysterically funny" seems like a phrase in common English usage, so I just figured it made you LOL.

Dictionary does say:

>INFORMAL
> extremely funny.

but,  yah, the formal definition is a tad bizarre for this usage.

¯\_(ツ)_/¯ 

English - weird language. :)

**Comment by snipe** [comment]
Autocorrect is a harsh mistress sometimes 😂😭

**Comment by haikusw** [comment]
Replaced by #5

**Pull request closed without merging**
